In [1]:
import numpy as np

In [2]:
arr1 = np.array(range(1, 13))

In [3]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [4]:
arr2 = np.resize(arr1, (3, 4))

In [5]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
arr1.shape

(12,)

In [7]:
arr3 = np.resize(np.array(range(13, 27)), (4, 3))

In [8]:
arr3

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [9]:
# dot prod 

np.dot(arr2, arr3)

array([[190, 200, 210],
       [470, 496, 522],
       [750, 792, 834]])

In [10]:
np.matmul(arr2, arr3)

array([[190, 200, 210],
       [470, 496, 522],
       [750, 792, 834]])

In [11]:
a = np.random.rand(1, 3)
b = np.random.rand(3, 1)
c = a @ b
d = np.dot(a, b)
print("a: ", a)
print("------------------------")
print("b: ", b)
print("------------------------")
print("c: ", c, "\n shape: ", c.shape)
print("d: ", d, "\n shape: ", d.shape)

a:  [[0.0011334  0.59659193 0.77030234]]
------------------------
b:  [[0.3372276 ]
 [0.37616109]
 [0.70359242]]
------------------------
c:  [[0.76677578]] 
 shape:  (1, 1)
d:  [[0.76677578]] 
 shape:  (1, 1)


In [12]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [13]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [14]:
climate_data.shape

(10000, 3)

In [15]:
weights = np.array([0.3, 0.2, 0.5])

In [16]:
yields = np.dot(climate_data, weights)

# can use any of dot or vector product here as the result is same

In [17]:
yields.shape

(10000,)

In [18]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [19]:
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)

In [20]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [54]:
np.savetxt?

Signature:      
np.savetxt(
    fname,
    X,
    fmt='%.18e',
    delimiter=' ',
    newline='\n',
    header='',
    footer='',
    comments='# ',
    encoding=None,
)
Call signature:  np.savetxt(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function savetxt at 0x000001BC62B4DDA0>
File:            c:\users\mpshi\anaconda3\lib\site-packages\numpy\lib\npyio.py
Docstring:      
Save an array to a text file.

Parameters
----------
fname : filename or file handle
    If the filename ends in ``.gz``, the file is automatically saved in
    compressed gzip format.  `loadtxt` understands gzipped files
    transparently.
X : 1D or 2D array_like
    Data to be saved to a text file.
fmt : str or sequence of strs, optional
    A single format (%10.5f), a sequence of formats, or a
    multi-format string, e.g. 'Iteration %d -- %10.5f', in which
    case `delimiter` is ignored. For complex `X`, the legal options
    for `fmt` are:

    * a single specifier, `fmt='%.4

In [62]:
np.savetxt(
    "climate_results_2.txt",
    climate_results,
    fmt = '%.2f',
    delimiter = ',',
    header = 'temp, raifall, humidity, yeild',
    comments = ''
)

## Array Indexing and Slicing